// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pmessage.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PMessage struct {
	From                 string              `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	MsgType              int32               `protobuf:"varint,2,opt,name=MsgType,proto3" json:"MsgType,omitempty"`
	ArrVal               int64               `protobuf:"varint,3,opt,name=ArrVal,proto3" json:"ArrVal,omitempty"`
	PropNum              int64               `protobuf:"varint,4,opt,name=PropNum,proto3" json:"PropNum,omitempty"`
	Vals                 []*PMessage_PAction `protobuf:"bytes,5,rep,name=Vals,proto3" json:"Vals,omitempty"`
	LogLen               int64               `protobuf:"varint,6,opt,name=LogLen,proto3" json:"LogLen,omitempty"`
	ClientID             int32               `protobuf:"varint,7,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Reviews              []*PMessage_RBody   `protobuf:"bytes,8,rep,name=Reviews,proto3" json:"Reviews,omitempty"`
	Valid                int32               `protobuf:"varint,9,opt,name=Valid,proto3" json:"Valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PMessage) Reset()         { *m = PMessage{} }
func (m *PMessage) String() string { return proto.CompactTextString(m) }
func (*PMessage) ProtoMessage()    {}
func (*PMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b339537a4fe8bf1, []int{0}
}

func (m *PMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PMessage.Unmarshal(m, b)
}
func (m *PMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PMessage.Marshal(b, m, deterministic)
}
func (m *PMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PMessage.Merge(m, src)
}
func (m *PMessage) XXX_Size() int {
	return xxx_messageInfo_PMessage.Size(m)
}
func (m *PMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PMessage proto.InternalMessageInfo

func (m *PMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *PMessage) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *PMessage) GetArrVal() int64 {
	if m != nil {
		return m.ArrVal
	}
	return 0
}

func (m *PMessage) GetPropNum() int64 {
	if m != nil {
		return m.PropNum
	}
	return 0
}

func (m *PMessage) GetVals() []*PMessage_PAction {
	if m != nil {
		return m.Vals
	}
	return nil
}

func (m *PMessage) GetLogLen() int64 {
	if m != nil {
		return m.LogLen
	}
	return 0
}

func (m *PMessage) GetClientID() int32 {
	if m != nil {
		return m.ClientID
	}
	return 0
}

func (m *PMessage) GetReviews() []*PMessage_RBody {
	if m != nil {
		return m.Reviews
	}
	return nil
}

func (m *PMessage) GetValid() int32 {
	if m != nil {
		return m.Valid
	}
	return 0
}

type PMessage_PAction struct {
	Op                   int32           `protobuf:"varint,1,opt,name=Op,proto3" json:"Op,omitempty"`
	Val                  *PMessage_RBody `protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PMessage_PAction) Reset()         { *m = PMessage_PAction{} }
func (m *PMessage_PAction) String() string { return proto.CompactTextString(m) }
func (*PMessage_PAction) ProtoMessage()    {}
func (*PMessage_PAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b339537a4fe8bf1, []int{0, 0}
}

func (m *PMessage_PAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PMessage_PAction.Unmarshal(m, b)
}
func (m *PMessage_PAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PMessage_PAction.Marshal(b, m, deterministic)
}
func (m *PMessage_PAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PMessage_PAction.Merge(m, src)
}
func (m *PMessage_PAction) XXX_Size() int {
	return xxx_messageInfo_PMessage_PAction.Size(m)
}
func (m *PMessage_PAction) XXX_DiscardUnknown() {
	xxx_messageInfo_PMessage_PAction.DiscardUnknown(m)
}

var xxx_messageInfo_PMessage_PAction proto.InternalMessageInfo

func (m *PMessage_PAction) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *PMessage_PAction) GetVal() *PMessage_RBody {
	if m != nil {
		return m.Val
	}
	return nil
}

type PMessage_RBody struct {
	RID                  int32    `protobuf:"varint,1,opt,name=RID,proto3" json:"RID,omitempty"`
	Album                string   `protobuf:"bytes,2,opt,name=Album,proto3" json:"Album,omitempty"`
	Artist               string   `protobuf:"bytes,3,opt,name=Artist,proto3" json:"Artist,omitempty"`
	Rating               int32    `protobuf:"varint,4,opt,name=Rating,proto3" json:"Rating,omitempty"`
	Body                 string   `protobuf:"bytes,5,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PMessage_RBody) Reset()         { *m = PMessage_RBody{} }
func (m *PMessage_RBody) String() string { return proto.CompactTextString(m) }
func (*PMessage_RBody) ProtoMessage()    {}
func (*PMessage_RBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b339537a4fe8bf1, []int{0, 1}
}

func (m *PMessage_RBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PMessage_RBody.Unmarshal(m, b)
}
func (m *PMessage_RBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PMessage_RBody.Marshal(b, m, deterministic)
}
func (m *PMessage_RBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PMessage_RBody.Merge(m, src)
}
func (m *PMessage_RBody) XXX_Size() int {
	return xxx_messageInfo_PMessage_RBody.Size(m)
}
func (m *PMessage_RBody) XXX_DiscardUnknown() {
	xxx_messageInfo_PMessage_RBody.DiscardUnknown(m)
}

var xxx_messageInfo_PMessage_RBody proto.InternalMessageInfo

func (m *PMessage_RBody) GetRID() int32 {
	if m != nil {
		return m.RID
	}
	return 0
}

func (m *PMessage_RBody) GetAlbum() string {
	if m != nil {
		return m.Album
	}
	return ""
}

func (m *PMessage_RBody) GetArtist() string {
	if m != nil {
		return m.Artist
	}
	return ""
}

func (m *PMessage_RBody) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *PMessage_RBody) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*PMessage)(nil), "pb.PMessage")
	proto.RegisterType((*PMessage_PAction)(nil), "pb.PMessage.PAction")
	proto.RegisterType((*PMessage_RBody)(nil), "pb.PMessage.RBody")
}

func init() { proto.RegisterFile("pmessage.proto", fileDescriptor_1b339537a4fe8bf1) }

var fileDescriptor_1b339537a4fe8bf1 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0xc7, 0x69, 0xbb, 0xac, 0xeb, 0x09, 0x43, 0x8e, 0x21, 0x61, 0x4f, 0x45, 0x7c, 0xe8, 0x83,
	0xf4, 0x41, 0x3f, 0x80, 0x4c, 0x87, 0x30, 0xd8, 0xdc, 0x38, 0x64, 0xef, 0xad, 0x0b, 0xa5, 0xd0,
	0x36, 0xa1, 0xc9, 0x94, 0x7d, 0x3d, 0x3f, 0x99, 0x24, 0x69, 0x05, 0xc1, 0xb7, 0xfb, 0x25, 0xb9,
	0xff, 0xff, 0xf2, 0x3f, 0x98, 0xab, 0x56, 0x68, 0x5d, 0x54, 0x22, 0x57, 0xbd, 0x34, 0x12, 0x43,
	0x55, 0xde, 0x7e, 0x47, 0x30, 0x3b, 0xec, 0xfc, 0x31, 0x22, 0x4c, 0x5e, 0x7b, 0xd9, 0xf2, 0x20,
	0x0d, 0xb2, 0x84, 0x5c, 0x8d, 0x1c, 0xe2, 0x9d, 0xae, 0xde, 0x2f, 0x4a, 0xf0, 0x30, 0x0d, 0x32,
	0x46, 0x23, 0xe2, 0x0d, 0x4c, 0x57, 0x7d, 0x7f, 0x2c, 0x1a, 0x1e, 0xa5, 0x41, 0x16, 0xd1, 0x40,
	0xb6, 0xe3, 0xd0, 0x4b, 0xf5, 0x76, 0x6e, 0xf9, 0xc4, 0x5d, 0x8c, 0x88, 0x19, 0x4c, 0x8e, 0x45,
	0xa3, 0x39, 0x4b, 0xa3, 0xec, 0xea, 0x61, 0x91, 0xab, 0x32, 0x1f, 0xbd, 0xf3, 0xc3, 0xea, 0xc3,
	0xd4, 0xb2, 0x23, 0xf7, 0xc2, 0x6a, 0x6f, 0x65, 0xb5, 0x15, 0x1d, 0x9f, 0x7a, 0x6d, 0x4f, 0xb8,
	0x84, 0xd9, 0x4b, 0x53, 0x8b, 0xce, 0x6c, 0xd6, 0x3c, 0x76, 0xe3, 0xfc, 0x32, 0xde, 0x43, 0x4c,
	0xe2, 0xb3, 0x16, 0x5f, 0x9a, 0xcf, 0x9c, 0x01, 0xfe, 0x31, 0xa0, 0x67, 0x79, 0xba, 0xd0, 0xf8,
	0x04, 0x17, 0xc0, 0x8e, 0x45, 0x53, 0x9f, 0x78, 0xe2, 0x64, 0x3c, 0x2c, 0x9f, 0x20, 0x1e, 0x06,
	0xc1, 0x39, 0x84, 0x7b, 0xe5, 0xa2, 0x60, 0x14, 0xee, 0x15, 0xde, 0x41, 0x64, 0xff, 0x6a, 0x43,
	0xf8, 0x5f, 0xda, 0x5e, 0x2f, 0x35, 0x30, 0x47, 0x78, 0x0d, 0x11, 0x6d, 0xd6, 0x43, 0xbf, 0x2d,
	0xad, 0xe3, 0xaa, 0x29, 0xcf, 0xad, 0x93, 0x48, 0xc8, 0x83, 0x4f, 0xd1, 0xd4, 0xda, 0xb8, 0x14,
	0x13, 0x1a, 0xc8, 0x9e, 0x53, 0x61, 0xea, 0xae, 0x72, 0x21, 0x32, 0x1a, 0xc8, 0xee, 0xc8, 0xea,
	0x73, 0xe6, 0x77, 0x64, 0xeb, 0x72, 0xea, 0xf6, 0xf9, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0xc3,
	0xf5, 0x80, 0x7b, 0xe1, 0x01, 0x00, 0x00,
}
